#ifndef CONTRACT_H
#define CONTRACT_H

enum {
    CONTRACT_PLATFORM_LINUX,
    CONTRACT_PLATFORM_MACOS,
    CONTRACT_PLATFORM_WINDOWS,
};

enum {
    CONTRACT_TYPE_INFO_BOOLEAN = 1,
    CONTRACT_TYPE_INFO_CHARACTER,
    CONTRACT_TYPE_INFO_INTEGER,
    CONTRACT_TYPE_INFO_POINTER,
    CONTRACT_TYPE_INFO_FUNCTION,
    CONTRACT_TYPE_INFO_ENUMERATION,
    CONTRACT_TYPE_INFO_TRAIT,
    CONTRACT_TYPE_INFO_UNION,
    CONTRACT_TYPE_INFO_STRUCTURE,
    CONTRACT_TYPE_INFO_ARRAY,
    CONTRACT_TYPE_INFO_DYNAMIC_ARRAY,
    CONTRACT_TYPE_INFO_SLICE,
    CONTRACT_TYPE_INFO_STRING,
};

#endif // CONTRACT_H
